In [102]:
import numpy as np
from collections import OrderedDict
# 1 is populated
# 0  is empty

In [111]:
# board = OrderedDict()
# keys= range(1,11)
# for i in keys:
#     for i in range(1,11):
#         x=np.random.choice([0, 1])
#         board[i] = x
# print(board)
# for i in keys:
#     print(i)
# for row in range(10):
#     row = defaultdict
    
#     for i in range(10):
#         row[i] = np.random.choice([0, 1])
#     board[row]=i


OrderedDict([(1, 1), (2, 0), (3, 0), (4, 0), (5, 0), (6, 1), (7, 1), (8, 1), (9, 1), (10, 0)])


In [121]:
board = np.zeros((10,10),dtype=int)
startx = np.random.randint(0,1, size=10)

print (board)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [129]:
row, col = 10, 10
board = np.random.randint(2, size=(10,10))

In [131]:
print(board)

[[0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 1 1]
 [1 1 0 0 0 0 1 0 1 0]
 [0 0 1 0 0 1 1 0 0 1]
 [1 1 1 0 1 0 0 1 1 0]
 [1 1 0 0 1 0 1 0 0 1]
 [0 0 0 1 0 0 0 0 1 0]
 [1 0 1 1 0 0 0 1 0 0]
 [1 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 1]]


In [134]:
for i in range(len(board):
    for j in range(len(row)):
        
        neighbors = [, row[int(i+1)], board[int(row-1)][int(i-1):int(i+2)], board[int(row-1)][int(i-1):int(i+2)]]
    
        print(neighbors)
            
            

TypeError: only length-1 arrays can be converted to Python scalars

In [79]:
row = 2
i = 3
x = board[row][i]
neighbors = [row[int(x-1)], row[int(x+1)], board[int(row-1)][int(i-1):int(i+2)], board[int(row-1)][int(i-1):int(i+2)]]
print(x)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [77]:
print (board[3])

[[0], [1], [0], [1], [0], [1], [1], [0], [1], [1]]
